### ISSUE TITLE
There are two points in the code where STOP codons are discarded. Remove redundancy.

### ISSUE THREAD

**Issue by gustavo11** [jaumlrc/ProphET#18]

**Comment by jaumlrc** [comment]
Checked the code for redundancy in removing stop codons and could only found this passage (lines 95 and 96 from INSTALL.pl):

`sed s'/[*]//g' Phage_proteins_pre_raw.db > Phage_proteins_pre_raw_without_stop.db `; # Remove asterisks representing STOP codons
`perl ../UTILS.dir/script_remover_vazios.pl Phage_proteins_pre_raw_without_stop.db > Phage_proteins_raw.db`; #Remove empty sequences (Headers only)

The first part removes stop codons, represented by “*”, while the second command removes headers without sequences
