### ISSUE TITLE
Github release

### ISSUE THREAD

**Issue by Takadonet** [jaumlrc/ProphET#21]
It is possible that a github release can be made? It will make it easier to create a bioconda recipe for the application .

**Comment by gustavo11** [comment]
Sorry Takadonet. I was in the process of changing jobs... and it seems that my github email was not updated. I'm seeing this requenst only today. I will create a release in the next couple of days.

**Comment by gustavo11** [comment]
@Takadonet , sorry for the delay. Some new features were added recently as part of the first release (0.5). New features will be included soon.
