### ISSUE TITLE
Database updating

### ISSUE THREAD

**Issue by kabilov** [jaumlrc/ProphET#24]
I think it will be useful to do command for updating phage database.

**Comment by gustavo11** [comment]
@kabilov Hi kabilov, "--update_db_only" option was added to script INSTALL.pl. 
INSTALL.pl --update_db_only

This change will committed in the next hour.

**Comment by gustavo11** [comment]
Hi @kabilov. I have made same changes and testes. The new feature is working as expected. The new version of the application backs up the current database before updates and add a file with stats and download date of the prophage db in the results dir. of every execution (auditing).

**Comment by kabilov** [comment]
Dear Gustavo,

Thank you for help.

Best wishes,
Marsel
