### ISSUE TITLE
Unable to find the transcript and gene associated to the CDS

### ISSUE THREAD

**Issue by stefjanson** [jaumlrc/ProphET#44]
Hi,

I'm having some trouble parsing my GFF (source: PROKKA).
When i run ProphET with the follwing command i get this error:

/ProphET/ProphET_standalone.pl --fasta_in scaffolds.fasta --gff_in scaffolds.gff --outdir .
Reading genes...
Reading transcripts...
Reading exons...
Reading UTRs...
Reading CDS...
Unable to find the transcript and gene associated to the CDS ID=BDOKHAHA_00001 NAME=gyrA_1 using as parent PARENT=BDOKHAHA_00001_gene
 at /ProphET/UTILS.dir/GFFLib/GFFFile.pm line 594, <GFFin> line 5756.
	GFFFile::read_cds(GFFFile=HASH(0x2259f30), undef, undef) called at /ProphET/UTILS.dir/GFFLib/GFFFile.pm line 105
	GFFFile::read(GFFFile=HASH(0x2259f30)) called at /ProphET/ProphET_standalone.pl line 195

How do i solve this?

Thanks in advance.
Stef

**Comment by jaumlrc** [comment]
Hello stefjanson,

We have developed a script to correct potential unformatted GFFs, which is
bundled with the ProphET installation.

Its use is described in the section “*Before running ProphET in your
favorite bacterial genome*”, at  https://github.com/jaumlrc/ProphET.

An example command would be:

perl -I /ProphET/UTILS.dir/GFFLib/ /ProphET/UTILS.dir/GFFLib/gff_rewrite.pl
--input File.gff -output File-corr.gff  --add_missing_features

 The “-I /ProphET/UTILS.dir/GFFLib/” part is just to point to some needed
perl libraries.



Thank you for using ProphET! All my best,

João Cunha

Em sex., 19 de jun. de 2020 às 06:47, stefjanson <notifications@github.com>
escreveu:

**Comment by stefjanson** [comment]
I also tried running the gff_rewrite script but i ended up with the same error. I overlooked the --add_missing_features flag. After adding this option the script ran without errors. Thanks alot.
